[2024-04-03T21:21:25.613+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IMDB-DAG.download-dataset-tasks.download_title.episode_task manual__2024-04-03T21:21:20.128211+00:00 [queued]>
[2024-04-03T21:21:25.636+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IMDB-DAG.download-dataset-tasks.download_title.episode_task manual__2024-04-03T21:21:20.128211+00:00 [queued]>
[2024-04-03T21:21:25.637+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-03T21:21:25.681+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): download-dataset-tasks.download_title.episode_task> on 2024-04-03 21:21:20.128211+00:00
[2024-04-03T21:21:25.716+0000] {standard_task_runner.py:60} INFO - Started process 3575 to run task
[2024-04-03T21:21:25.790+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'IMDB-DAG', 'download-dataset-tasks.download_title.episode_task', 'manual__2024-04-03T21:21:20.128211+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/imdb_dab.py', '--cfg-path', '/tmp/tmps9cwx34p']
[2024-04-03T21:21:25.817+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask download-dataset-tasks.download_title.episode_task
[2024-04-03T21:21:26.223+0000] {task_command.py:423} INFO - Running <TaskInstance: IMDB-DAG.download-dataset-tasks.download_title.episode_task manual__2024-04-03T21:21:20.128211+00:00 [running]> on host 092193d62c58
[2024-04-03T21:21:26.576+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='iamraphson' AIRFLOW_CTX_DAG_ID='IMDB-DAG' AIRFLOW_CTX_TASK_ID='download-dataset-tasks.download_title.episode_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T21:21:20.128211+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-03T21:21:20.128211+00:00'
[2024-04-03T21:21:26.583+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-03T21:21:26.586+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'curl -sSL https://datasets.imdbws.com/title.episode.tsv.gz > /opt/***/raws/title.episode.tsv.gz']
[2024-04-03T21:21:26.666+0000] {subprocess.py:86} INFO - Output:
[2024-04-03T21:21:26.669+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /opt/***/raws/title.episode.tsv.gz: No such file or directory
[2024-04-03T21:21:26.670+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-03T21:21:26.717+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-03T21:21:26.727+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=IMDB-DAG, task_id=download-dataset-tasks.download_title.episode_task, execution_date=20240403T212120, start_date=20240403T212125, end_date=20240403T212126
[2024-04-03T21:21:26.771+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task download-dataset-tasks.download_title.episode_task (Bash command failed. The command returned a non-zero exit code 1.; 3575)
[2024-04-03T21:21:26.810+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-03T21:21:27.010+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
